# Generated by Django 3.1.3 on 2020-12-08 12:33

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('locations', models.CharField(max_length=100)),
                ('sector_focus', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('deal', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('logo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('avg_mentorship', models.DecimalField(decimal_places=2, max_digits=3)),
                ('avg_hiring', models.DecimalField(decimal_places=2, max_digits=3)),
                ('avg_community', models.DecimalField(decimal_places=2, max_digits=3)),
                ('avg_corporate_fundraising', models.DecimalField(decimal_places=2, max_digits=3)),
                ('avg_fundraising', models.DecimalField(decimal_places=2, max_digits=3)),
                ('user', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
