# Generated by Django 3.1.3 on 2020-12-08 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appraisalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
