# Generated by Django 3.1.3 on 2020-12-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisalapp', '0002_company_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='avg_community',
        ),
        migrations.RemoveField(
            model_name='company',
            name='avg_corporate_fundraising',
        ),
        migrations.RemoveField(
            model_name='company',
            name='avg_fundraising',
        ),
        migrations.RemoveField(
            model_name='company',
            name='avg_hiring',
        ),
        migrations.RemoveField(
            model_name='company',
            name='avg_mentorship',
        ),
        migrations.RemoveField(
            model_name='company',
            name='avg_rating',
        ),
    ]
