# Generated by Django 3.1.3 on 2020-12-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisalapp', '0004_auto_20201209_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='avg_corporate_dev',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
