# Generated by Django 3.1.3 on 2020-12-09 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisalapp', '0006_auto_20201209_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='avg_corporate_dev',
        ),
    ]
